name: local
root: ~/Projects/nodejs/kamo_all/

windows:
  - psql:
      layout: main-vertical
      panes:
        - a:
            - pg_ctl start
            - psql -U postgres -h localhost kamo
  - kamo:
      layout: main-vertical
      panes:
        - a:
            - cd kamo
            - yarn dev
        - b:
            - cd kamo-front
            - yarn dev
        - e:
            - cd kamo_manager
        - c:
            - cd kamo-candidate
            - yarn dev
        - d:
            - cd kamo-admin
            - redis-server
  - dotfiles:
      layout: main-vertical
      panes:
        - a:
            - cd ~/dotfiles
            - git pull

