name: local
root: ~/Projects/nodejs/

windows:
  - psql:
      layout: main-vertical
      panes:
        - a:
            - pg_ctl start
            # - psql -U postgres -h localhost kamo
  - kamo:
      layout: main-vertical
      panes:
        - a:
            - cd kamo_all/kamo
            - pm2 startOrRestart ecosystem_local.config.js && pm2 logs
        - b:
            - cd kamo_all/kamo-front
            - npm run dev
        - c:
            - cd kamo_all/kamo_manager
        - d:
            - cd kamo_all/kamo-candidate
        - e:
            - cd kamo_all/kamo-admin
            - redis-server
  - dotfiles:
      layout: main-vertical
      panes:
        - a:
            - cd ~/dotfiles
            - git pull
  - golang-fiber:
      layout: main-vertical
      panes:
        - a:
            - cd ../golang/fiber-boilerplate
            # - source .env.local && ./bbgo run --config bbgo.yaml

