name: local
root: ~/Projects/nodejs/kamo_all/

windows:
  - psql:
      layout: main-vertical
      panes:
        - a:
            - pg_ctl start
            - psql -U postgres -h localhost kamo
  - kamo:
      layout: main-vertical
      panes:
        - a:
            - cd kamo
            - pm2 startOrRestart ecosystem_local.config.js && pm2 logs
        - b:
            - cd kamo-front
            - npm run dev
        - e:
            - cd kamo_manager
        - c:
            - cd kamo-candidate
            - npm run dev
        - d:
            - cd kamo-admin
            - redis-server
  - dotfiles:
      layout: main-vertical
      panes:
        - a:
            - cd ~/dotfiles
            - git pull
  - max:
      layout: main-vertical
      panes:
        - a:
            - cd ~/go/src/github.com/motephyr/bbgo/cmd/bbgo
            # - source .env.local && ./bbgo run --config bbgo.yaml

