name: phoenix
root: ~/Projects/nodejs/kamo_all/

windows:
  - pgctl:
      layout: main-vertical
      panes:
        - a:
            - pg_ctl start
            - export PGGSSENCMODE=disable && pgcli -U postgres -h localhost kamo
  - kamo:
      layout: main-vertical
      panes:
        - a:
            - cd kamo
            - yarn dev
        - b:
            - cd kamo-front
            - yarn dev
        - e:
            - cd kamo_manager
            - yarn dev
        - c:
            - cd kamo_candidate
            - yarn dev
        - d:
            - cd kamo-admin
  - dotfiles:
      layout: main-vertical
      panes:
        - a:
            - cd ~/dotfiles
            - git pull

