
name: phoenix
root: ~/Projects

windows:
  - main:
      layout: main-vertical
      panes:
        - a:
          - cd ~/dotfiles
          - git pull
          - cd ~/Projects

  - joplin:
      layout: main-vertical
      panes:
        - a:
          - joplin
