name: local
root: ~/Projects/nodejs/

windows:
  - psql:
      layout: main-vertical
      panes:
        - a:
            - pg_ctl start
            # - psql -U postgres -h localhost kamo
  - kamo:
      layout: main-vertical
      panes:
        - a:
            - cd kamo_all/kamo-server
            # - pm2 startOrRestart ecosystem_local.config.js && pm2 logs
        - b:
            - cd kamo_all/kamo-front
            # - npm run dev
        - c:
            - cd kamo_all/kamo_manager
        - d:
            - cd kamo_all/kamo-candidate
        - e:
            - cd kamo_all/kamo_test
  - dotfiles:
      layout: main-vertical
      panes:
        - a:
            - cd ~/dotfiles
            - git pull
  - plus_minus:
      layout: main-vertical
      panes:
        - a:
            - cd plus_minus_20230309/plus_minus
        - b:
            - cd plus_minus_20230309/plus_minus_front
            # - source .env.local && ./bbgo run --config bbgo.yaml

